clear image source attributes in profile.html
the original source attibute values caused an object enumeration error in git, making it impossible to clone the repository.
the following error message(s) was (were) given by git:

error: invalid path 'assets/site/placeholders/16:9_placeholder.jpg'
Git: remote: enumerating objects: 247, done.

this commit hopefully fixes the error. further investigation required.